### CONFIGURATION ###
#
ARG ENVOY_IMAGE=envoyproxy/envoy:v1.25.7
ARG CONSUL_IMAGE=hashicorp/consul:1.15.2
ARG SERVICE_IMAGE=localhost:55000/ucs-auth:latest
#
#####################

### BASE IMAGE ###
#
FROM ${ENVOY_IMAGE} as envoy-bin
FROM ${CONSUL_IMAGE} as consul-bin
FROM ${SERVICE_IMAGE} as service-bin

# Debian:12-slim
FROM node:18-slim
#
##################

RUN apt-get update && \
    apt-get install -y \
      bash \
      curl \
      net-tools \
      netcat-openbsd \
      jq \
      tzdata && \      
  rm -rf /var/lib/apt/lists/*

RUN \
    npm install pm2 -g && \
    npm install bun@0.7.1 -g
    
ENV CONSUL_HTTP_ADDR=http://localhost:8500

COPY --from=envoy-bin /usr/local/bin/envoy /bin/envoy
COPY --from=consul-bin /bin/consul /bin/consul
COPY --from=service-bin /app /app

COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
